# Copyright (c) 2026 BAAI. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

cpp = meson.get_compiler('cpp')

flagcx_lib = cpp.find_library('flagcx', dirs: ['/usr/local/lib'], required: false)
flagcx_rdma_lib = cpp.find_library('rdma_plugin', dirs: ['/usr/local/lib'], required: false)

if not flagcx_lib.found() or not flagcx_rdma_lib.found()
    message('FlagCX libraries not found, skipping flagcx_gtest build')
    subdir_done()
endif

python_dep = dependency('python3', required: false)
pybind11_dep = dependency('pybind11', required: false)

if not python_dep.found() or not pybind11_dep.found()
    message('Python dependencies not found, skipping flagcx_gtest build')
    subdir_done()
endif

cpp_flags = []
cpp_flags += '-DBUILD_DIR="' + meson.project_build_root() + '"'

if cuda_dep.found()
    cuda_dependencies = [cuda_dep]
    cpp_flags += '-DHAVE_CUDA'
else
    cuda_dependencies = []
    cpp_flags += '-UHAVE_CUDA'
endif

flagcx_test_exe = executable('flagcx_gtest',
    sources : ['flagcx_test.cpp', '../../main.cpp', '../../common.cpp'],
    include_directories: [nixl_inc_dirs, utils_inc_dirs, gtest_inc_dirs, '.'],
    cpp_args : cpp_flags,
    dependencies : [
        nixl_dep,
        nixl_infra,
        nixl_common_deps,
        thread_dep,
        python_dep,
        pybind11_dep,
        flagcx_rdma_lib,
        flagcx_lib,
        gtest_dep,
        gmock_dep,
        absl_strings_dep,
        absl_time_dep
    ] + cuda_dependencies,
    link_with: [nixl_build_lib],
    install : true
)

test('flagcx_gtest', flagcx_test_exe)
